name: MinetopiaFarms
version: 3.0
api-version: 1.12
author: MrWouter
description: 'MinetopiaFarms is een gemakkelijke manier om beroepen aan jouw server toe te voegen!'
main: nl.mrwouter.minetopiafarms.Main
soft-depend: [Citizens, MinetopiaSDB, WorldGuard, WorldEdit, Vault]
loadbefore: [WorldGuard]
commands:
     minetopiafarms:
        aliases: [mtfarms, farms]